(cl:defpackage komodo2_perception-srv
  (:use )
  (:export
   "GETFLOATARRAYFEATURE"
   "<GETFLOATARRAYFEATURE-REQUEST>"
   "GETFLOATARRAYFEATURE-REQUEST"
   "<GETFLOATARRAYFEATURE-RESPONSE>"
   "GETFLOATARRAYFEATURE-RESPONSE"
   "GETNORMALS"
   "<GETNORMALS-REQUEST>"
   "GETNORMALS-REQUEST"
   "<GETNORMALS-RESPONSE>"
   "GETNORMALS-RESPONSE"
  ))

