// Generated by gencpp from file komodo2_perception/GetFloatArrayFeature.msg
// DO NOT EDIT!


#ifndef KOMODO2_PERCEPTION_MESSAGE_GETFLOATARRAYFEATURE_H
#define KOMODO2_PERCEPTION_MESSAGE_GETFLOATARRAYFEATURE_H

#include <ros/service_traits.h>


#include <komodo2_perception/GetFloatArrayFeatureRequest.h>
#include <komodo2_perception/GetFloatArrayFeatureResponse.h>


namespace komodo2_perception
{

struct GetFloatArrayFeature
{

typedef GetFloatArrayFeatureRequest Request;
typedef GetFloatArrayFeatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFloatArrayFeature
} // namespace komodo2_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::komodo2_perception::GetFloatArrayFeature > {
  static const char* value()
  {
    return "c90ae3a91de76e55487209150231b931";
  }

  static const char* value(const ::komodo2_perception::GetFloatArrayFeature&) { return value(); }
};

template<>
struct DataType< ::komodo2_perception::GetFloatArrayFeature > {
  static const char* value()
  {
    return "komodo2_perception/GetFloatArrayFeature";
  }

  static const char* value(const ::komodo2_perception::GetFloatArrayFeature&) { return value(); }
};


// service_traits::MD5Sum< ::komodo2_perception::GetFloatArrayFeatureRequest> should match 
// service_traits::MD5Sum< ::komodo2_perception::GetFloatArrayFeature > 
template<>
struct MD5Sum< ::komodo2_perception::GetFloatArrayFeatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::komodo2_perception::GetFloatArrayFeature >::value();
  }
  static const char* value(const ::komodo2_perception::GetFloatArrayFeatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::komodo2_perception::GetFloatArrayFeatureRequest> should match 
// service_traits::DataType< ::komodo2_perception::GetFloatArrayFeature > 
template<>
struct DataType< ::komodo2_perception::GetFloatArrayFeatureRequest>
{
  static const char* value()
  {
    return DataType< ::komodo2_perception::GetFloatArrayFeature >::value();
  }
  static const char* value(const ::komodo2_perception::GetFloatArrayFeatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::komodo2_perception::GetFloatArrayFeatureResponse> should match 
// service_traits::MD5Sum< ::komodo2_perception::GetFloatArrayFeature > 
template<>
struct MD5Sum< ::komodo2_perception::GetFloatArrayFeatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::komodo2_perception::GetFloatArrayFeature >::value();
  }
  static const char* value(const ::komodo2_perception::GetFloatArrayFeatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::komodo2_perception::GetFloatArrayFeatureResponse> should match 
// service_traits::DataType< ::komodo2_perception::GetFloatArrayFeature > 
template<>
struct DataType< ::komodo2_perception::GetFloatArrayFeatureResponse>
{
  static const char* value()
  {
    return DataType< ::komodo2_perception::GetFloatArrayFeature >::value();
  }
  static const char* value(const ::komodo2_perception::GetFloatArrayFeatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOMODO2_PERCEPTION_MESSAGE_GETFLOATARRAYFEATURE_H
