// Generated by gencpp from file komodo2_perception/GetNormals.msg
// DO NOT EDIT!


#ifndef KOMODO2_PERCEPTION_MESSAGE_GETNORMALS_H
#define KOMODO2_PERCEPTION_MESSAGE_GETNORMALS_H

#include <ros/service_traits.h>


#include <komodo2_perception/GetNormalsRequest.h>
#include <komodo2_perception/GetNormalsResponse.h>


namespace komodo2_perception
{

struct GetNormals
{

typedef GetNormalsRequest Request;
typedef GetNormalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNormals
} // namespace komodo2_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::komodo2_perception::GetNormals > {
  static const char* value()
  {
    return "0a9bb8a1d7550c14c769843382adf4ac";
  }

  static const char* value(const ::komodo2_perception::GetNormals&) { return value(); }
};

template<>
struct DataType< ::komodo2_perception::GetNormals > {
  static const char* value()
  {
    return "komodo2_perception/GetNormals";
  }

  static const char* value(const ::komodo2_perception::GetNormals&) { return value(); }
};


// service_traits::MD5Sum< ::komodo2_perception::GetNormalsRequest> should match 
// service_traits::MD5Sum< ::komodo2_perception::GetNormals > 
template<>
struct MD5Sum< ::komodo2_perception::GetNormalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::komodo2_perception::GetNormals >::value();
  }
  static const char* value(const ::komodo2_perception::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::komodo2_perception::GetNormalsRequest> should match 
// service_traits::DataType< ::komodo2_perception::GetNormals > 
template<>
struct DataType< ::komodo2_perception::GetNormalsRequest>
{
  static const char* value()
  {
    return DataType< ::komodo2_perception::GetNormals >::value();
  }
  static const char* value(const ::komodo2_perception::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::komodo2_perception::GetNormalsResponse> should match 
// service_traits::MD5Sum< ::komodo2_perception::GetNormals > 
template<>
struct MD5Sum< ::komodo2_perception::GetNormalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::komodo2_perception::GetNormals >::value();
  }
  static const char* value(const ::komodo2_perception::GetNormalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::komodo2_perception::GetNormalsResponse> should match 
// service_traits::DataType< ::komodo2_perception::GetNormals > 
template<>
struct DataType< ::komodo2_perception::GetNormalsResponse>
{
  static const char* value()
  {
    return DataType< ::komodo2_perception::GetNormals >::value();
  }
  static const char* value(const ::komodo2_perception::GetNormalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOMODO2_PERCEPTION_MESSAGE_GETNORMALS_H
